/*
 * This file is generated by jOOQ.
 */
package generated_jooq;


import generated_jooq.tables.Admin;
import generated_jooq.tables.Banner;
import generated_jooq.tables.Blog;
import generated_jooq.tables.BlogBg;
import generated_jooq.tables.Information;
import generated_jooq.tables.Posts;
import generated_jooq.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Bysj extends SchemaImpl {

    private static final long serialVersionUID = -411966947;

    /**
     * The reference instance of <code>bysj</code>
     */
    public static final Bysj BYSJ = new Bysj();

    /**
     * ???
     */
    public final Admin ADMIN = generated_jooq.tables.Admin.ADMIN;

    /**
     * The table <code>bysj.banner</code>.
     */
    public final Banner BANNER = generated_jooq.tables.Banner.BANNER;

    /**
     * The table <code>bysj.blog</code>.
     */
    public final Blog BLOG = generated_jooq.tables.Blog.BLOG;

    /**
     * The table <code>bysj.blog_bg</code>.
     */
    public final BlogBg BLOG_BG = generated_jooq.tables.BlogBg.BLOG_BG;

    /**
     * The table <code>bysj.information</code>.
     */
    public final Information INFORMATION = generated_jooq.tables.Information.INFORMATION;

    /**
     * The table <code>bysj.posts</code>.
     */
    public final Posts POSTS = generated_jooq.tables.Posts.POSTS;

    /**
     * The table <code>bysj.user</code>.
     */
    public final User USER = generated_jooq.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Bysj() {
        super("bysj", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Admin.ADMIN,
            Banner.BANNER,
            Blog.BLOG,
            BlogBg.BLOG_BG,
            Information.INFORMATION,
            Posts.POSTS,
            User.USER);
    }
}
