/*
 * This file is generated by jOOQ.
 */
package generated_jooq;


import generated_jooq.tables.Admin;
import generated_jooq.tables.Banner;
import generated_jooq.tables.Blog;
import generated_jooq.tables.BlogBg;
import generated_jooq.tables.Information;
import generated_jooq.tables.Posts;
import generated_jooq.tables.User;


/**
 * Convenience access to all tables in bysj
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * ???
     */
    public static final Admin ADMIN = Admin.ADMIN;

    /**
     * The table <code>bysj.banner</code>.
     */
    public static final Banner BANNER = Banner.BANNER;

    /**
     * The table <code>bysj.blog</code>.
     */
    public static final Blog BLOG = Blog.BLOG;

    /**
     * The table <code>bysj.blog_bg</code>.
     */
    public static final BlogBg BLOG_BG = BlogBg.BLOG_BG;

    /**
     * The table <code>bysj.information</code>.
     */
    public static final Information INFORMATION = Information.INFORMATION;

    /**
     * The table <code>bysj.posts</code>.
     */
    public static final Posts POSTS = Posts.POSTS;

    /**
     * The table <code>bysj.user</code>.
     */
    public static final User USER = User.USER;
}
