/*
 * This file is generated by jOOQ.
 */
package generated_jooq.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IPosts extends Serializable {

    /**
     * Setter for <code>bysj.posts.id</code>.
     */
    public IPosts setId(Long value);

    /**
     * Getter for <code>bysj.posts.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>bysj.posts.name</code>. ??
     */
    public IPosts setName(String value);

    /**
     * Getter for <code>bysj.posts.name</code>. ??
     */
    @NotNull
    @Size(max = 255)
    public String getName();

    /**
     * Setter for <code>bysj.posts.describe</code>. ??
     */
    public IPosts setDescribe(String value);

    /**
     * Getter for <code>bysj.posts.describe</code>. ??
     */
    @Size(max = 255)
    public String getDescribe();

    /**
     * Setter for <code>bysj.posts.pv</code>. ?????
     */
    public IPosts setPv(Long value);

    /**
     * Getter for <code>bysj.posts.pv</code>. ?????
     */
    public Long getPv();

    /**
     * Setter for <code>bysj.posts.type</code>. ???? 1-??? 0-???
     */
    public IPosts setType(Integer value);

    /**
     * Getter for <code>bysj.posts.type</code>. ???? 1-??? 0-???
     */
    public Integer getType();

    /**
     * Setter for <code>bysj.posts.stick</code>. ???? 0-? 1-?
     */
    public IPosts setStick(Integer value);

    /**
     * Getter for <code>bysj.posts.stick</code>. ???? 0-? 1-?
     */
    public Integer getStick();

    /**
     * Setter for <code>bysj.posts.check</code>. ???? 0-?? 1-??
     */
    public IPosts setCheck(Integer value);

    /**
     * Getter for <code>bysj.posts.check</code>. ???? 0-?? 1-??
     */
    public Integer getCheck();

    /**
     * Setter for <code>bysj.posts.user_id</code>. ??Id
     */
    public IPosts setUserId(Long value);

    /**
     * Getter for <code>bysj.posts.user_id</code>. ??Id
     */
    @NotNull
    public Long getUserId();

    /**
     * Setter for <code>bysj.posts.created_at</code>. ????
     */
    public IPosts setCreatedAt(LocalDateTime value);

    /**
     * Getter for <code>bysj.posts.created_at</code>. ????
     */
    public LocalDateTime getCreatedAt();

    /**
     * Setter for <code>bysj.posts.updated_at</code>. ????
     */
    public IPosts setUpdatedAt(LocalDateTime value);

    /**
     * Getter for <code>bysj.posts.updated_at</code>. ????
     */
    public LocalDateTime getUpdatedAt();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IPosts
     */
    public void from(generated_jooq.tables.interfaces.IPosts from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IPosts
     */
    public <E extends generated_jooq.tables.interfaces.IPosts> E into(E into);
}
