/*
 * This file is generated by jOOQ.
 */
package generated;


import generated.tables.Admin;
import generated.tables.Banner;
import generated.tables.Blog;
import generated.tables.BlogBg;
import generated.tables.Information;
import generated.tables.Posts;
import generated.tables.User;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>bysj</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ADMIN_ADMIN_ACCOUNT_UNIQUE = Indexes0.ADMIN_ADMIN_ACCOUNT_UNIQUE;
    public static final Index ADMIN_ADMIN_NAME_INDEX = Indexes0.ADMIN_ADMIN_NAME_INDEX;
    public static final Index ADMIN_PRIMARY = Indexes0.ADMIN_PRIMARY;
    public static final Index BANNER_BANNER_BLOG_ID_INDEX = Indexes0.BANNER_BANNER_BLOG_ID_INDEX;
    public static final Index BANNER_PRIMARY = Indexes0.BANNER_PRIMARY;
    public static final Index BLOG_PRIMARY = Indexes0.BLOG_PRIMARY;
    public static final Index BLOG_BG_BLOG_BG_TYPE_INDEX = Indexes0.BLOG_BG_BLOG_BG_TYPE_INDEX;
    public static final Index BLOG_BG_PRIMARY = Indexes0.BLOG_BG_PRIMARY;
    public static final Index INFORMATION_INFORMATION_TYPE_INDEX = Indexes0.INFORMATION_INFORMATION_TYPE_INDEX;
    public static final Index INFORMATION_PRIMARY = Indexes0.INFORMATION_PRIMARY;
    public static final Index POSTS_POSTS_CHECK_INDEX = Indexes0.POSTS_POSTS_CHECK_INDEX;
    public static final Index POSTS_POSTS_NAME_INDEX = Indexes0.POSTS_POSTS_NAME_INDEX;
    public static final Index POSTS_POSTS_UPDATED_AT_INDEX = Indexes0.POSTS_POSTS_UPDATED_AT_INDEX;
    public static final Index POSTS_POSTS_USER_ID_INDEX = Indexes0.POSTS_POSTS_USER_ID_INDEX;
    public static final Index POSTS_PRIMARY = Indexes0.POSTS_PRIMARY;
    public static final Index USER_PRIMARY = Indexes0.USER_PRIMARY;
    public static final Index USER_USER_EMAIL_UNIQUE = Indexes0.USER_USER_EMAIL_UNIQUE;
    public static final Index USER_USER_NAME_INDEX = Indexes0.USER_USER_NAME_INDEX;
    public static final Index USER_USER_PHONE_UNIQUE = Indexes0.USER_USER_PHONE_UNIQUE;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ADMIN_ADMIN_ACCOUNT_UNIQUE = Internal.createIndex("admin_account_unique", Admin.ADMIN, new OrderField[] { Admin.ADMIN.ACCOUNT }, true);
        public static Index ADMIN_ADMIN_NAME_INDEX = Internal.createIndex("admin_name_index", Admin.ADMIN, new OrderField[] { Admin.ADMIN.NAME }, false);
        public static Index ADMIN_PRIMARY = Internal.createIndex("PRIMARY", Admin.ADMIN, new OrderField[] { Admin.ADMIN.ID }, true);
        public static Index BANNER_BANNER_BLOG_ID_INDEX = Internal.createIndex("banner_blog_id_index", Banner.BANNER, new OrderField[] { Banner.BANNER.BLOG_ID }, false);
        public static Index BANNER_PRIMARY = Internal.createIndex("PRIMARY", Banner.BANNER, new OrderField[] { Banner.BANNER.ID }, true);
        public static Index BLOG_PRIMARY = Internal.createIndex("PRIMARY", Blog.BLOG, new OrderField[] { Blog.BLOG.ID }, true);
        public static Index BLOG_BG_BLOG_BG_TYPE_INDEX = Internal.createIndex("blog_bg_type_index", BlogBg.BLOG_BG, new OrderField[] { BlogBg.BLOG_BG.TYPE }, false);
        public static Index BLOG_BG_PRIMARY = Internal.createIndex("PRIMARY", BlogBg.BLOG_BG, new OrderField[] { BlogBg.BLOG_BG.ID }, true);
        public static Index INFORMATION_INFORMATION_TYPE_INDEX = Internal.createIndex("information_type_index", Information.INFORMATION, new OrderField[] { Information.INFORMATION.TYPE }, false);
        public static Index INFORMATION_PRIMARY = Internal.createIndex("PRIMARY", Information.INFORMATION, new OrderField[] { Information.INFORMATION.ID }, true);
        public static Index POSTS_POSTS_CHECK_INDEX = Internal.createIndex("posts_check_index", Posts.POSTS, new OrderField[] { Posts.POSTS.CHECK }, false);
        public static Index POSTS_POSTS_NAME_INDEX = Internal.createIndex("posts_name_index", Posts.POSTS, new OrderField[] { Posts.POSTS.NAME }, false);
        public static Index POSTS_POSTS_UPDATED_AT_INDEX = Internal.createIndex("posts_updated_at_index", Posts.POSTS, new OrderField[] { Posts.POSTS.UPDATED_AT }, false);
        public static Index POSTS_POSTS_USER_ID_INDEX = Internal.createIndex("posts_user_id_index", Posts.POSTS, new OrderField[] { Posts.POSTS.USER_ID }, false);
        public static Index POSTS_PRIMARY = Internal.createIndex("PRIMARY", Posts.POSTS, new OrderField[] { Posts.POSTS.ID }, true);
        public static Index USER_PRIMARY = Internal.createIndex("PRIMARY", User.USER, new OrderField[] { User.USER.ID }, true);
        public static Index USER_USER_EMAIL_UNIQUE = Internal.createIndex("user_email_unique", User.USER, new OrderField[] { User.USER.EMAIL }, true);
        public static Index USER_USER_NAME_INDEX = Internal.createIndex("user_name_index", User.USER, new OrderField[] { User.USER.NAME }, false);
        public static Index USER_USER_PHONE_UNIQUE = Internal.createIndex("user_phone_unique", User.USER, new OrderField[] { User.USER.PHONE }, true);
    }
}
