/*
 * This file is generated by jOOQ.
 */
package generated_jooq.tables.pojos;


import generated_jooq.tables.interfaces.IBlog;

import java.time.LocalDateTime;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Blog implements IBlog {

    private static final long serialVersionUID = -916453057;

    private Long          id;
    private String        name;
    private String        describe;
    private String        context;
    private Integer       type;
    private Integer       articleType;
    private Long          pv;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public Blog() {}

    public Blog(IBlog value) {
        this.id = value.getId();
        this.name = value.getName();
        this.describe = value.getDescribe();
        this.context = value.getContext();
        this.type = value.getType();
        this.articleType = value.getArticleType();
        this.pv = value.getPv();
        this.createdAt = value.getCreatedAt();
        this.updatedAt = value.getUpdatedAt();
    }

    public Blog(
        Long          id,
        String        name,
        String        describe,
        String        context,
        Integer       type,
        Integer       articleType,
        Long          pv,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.name = name;
        this.describe = describe;
        this.context = context;
        this.type = type;
        this.articleType = articleType;
        this.pv = pv;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public Blog setId(Long id) {
        this.id = id;
        return this;
    }

    @NotNull
    @Size(max = 65535)
    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public Blog setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public String getDescribe() {
        return this.describe;
    }

    @Override
    public Blog setDescribe(String describe) {
        this.describe = describe;
        return this;
    }

    @NotNull
    @Override
    public String getContext() {
        return this.context;
    }

    @Override
    public Blog setContext(String context) {
        this.context = context;
        return this;
    }

    @Override
    public Integer getType() {
        return this.type;
    }

    @Override
    public Blog setType(Integer type) {
        this.type = type;
        return this;
    }

    @Override
    public Integer getArticleType() {
        return this.articleType;
    }

    @Override
    public Blog setArticleType(Integer articleType) {
        this.articleType = articleType;
        return this;
    }

    @Override
    public Long getPv() {
        return this.pv;
    }

    @Override
    public Blog setPv(Long pv) {
        this.pv = pv;
        return this;
    }

    @Override
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @Override
    public Blog setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @Override
    public Blog setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Blog other = (Blog) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        if (describe == null) {
            if (other.describe != null)
                return false;
        }
        else if (!describe.equals(other.describe))
            return false;
        if (context == null) {
            if (other.context != null)
                return false;
        }
        else if (!context.equals(other.context))
            return false;
        if (type == null) {
            if (other.type != null)
                return false;
        }
        else if (!type.equals(other.type))
            return false;
        if (articleType == null) {
            if (other.articleType != null)
                return false;
        }
        else if (!articleType.equals(other.articleType))
            return false;
        if (pv == null) {
            if (other.pv != null)
                return false;
        }
        else if (!pv.equals(other.pv))
            return false;
        if (createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!createdAt.equals(other.createdAt))
            return false;
        if (updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.describe == null) ? 0 : this.describe.hashCode());
        result = prime * result + ((this.context == null) ? 0 : this.context.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        result = prime * result + ((this.articleType == null) ? 0 : this.articleType.hashCode());
        result = prime * result + ((this.pv == null) ? 0 : this.pv.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Blog (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(describe);
        sb.append(", ").append(context);
        sb.append(", ").append(type);
        sb.append(", ").append(articleType);
        sb.append(", ").append(pv);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IBlog from) {
        setId(from.getId());
        setName(from.getName());
        setDescribe(from.getDescribe());
        setContext(from.getContext());
        setType(from.getType());
        setArticleType(from.getArticleType());
        setPv(from.getPv());
        setCreatedAt(from.getCreatedAt());
        setUpdatedAt(from.getUpdatedAt());
    }

    @Override
    public <E extends IBlog> E into(E into) {
        into.from(this);
        return into;
    }
}
