/*
 * This file is generated by jOOQ.
 */
package generated.tables.pojos;


import generated.tables.interfaces.IInformation;

import java.time.LocalDateTime;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Information implements IInformation {

    private static final long serialVersionUID = 1796521633;

    private Long          id;
    private String        name;
    private String        describe;
    private String        img;
    private String        video;
    private Integer       type;
    private Long          pv;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public Information() {}

    public Information(IInformation value) {
        this.id = value.getId();
        this.name = value.getName();
        this.describe = value.getDescribe();
        this.img = value.getImg();
        this.video = value.getVideo();
        this.type = value.getType();
        this.pv = value.getPv();
        this.createdAt = value.getCreatedAt();
        this.updatedAt = value.getUpdatedAt();
    }

    public Information(
        Long          id,
        String        name,
        String        describe,
        String        img,
        String        video,
        Integer       type,
        Long          pv,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.name = name;
        this.describe = describe;
        this.img = img;
        this.video = video;
        this.type = type;
        this.pv = pv;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public Information setId(Long id) {
        this.id = id;
        return this;
    }

    @NotNull
    @Size(max = 255)
    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public Information setName(String name) {
        this.name = name;
        return this;
    }

    @Size(max = 255)
    @Override
    public String getDescribe() {
        return this.describe;
    }

    @Override
    public Information setDescribe(String describe) {
        this.describe = describe;
        return this;
    }

    @NotNull
    @Size(max = 65535)
    @Override
    public String getImg() {
        return this.img;
    }

    @Override
    public Information setImg(String img) {
        this.img = img;
        return this;
    }

    @NotNull
    @Size(max = 65535)
    @Override
    public String getVideo() {
        return this.video;
    }

    @Override
    public Information setVideo(String video) {
        this.video = video;
        return this;
    }

    @Override
    public Integer getType() {
        return this.type;
    }

    @Override
    public Information setType(Integer type) {
        this.type = type;
        return this;
    }

    @Override
    public Long getPv() {
        return this.pv;
    }

    @Override
    public Information setPv(Long pv) {
        this.pv = pv;
        return this;
    }

    @Override
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @Override
    public Information setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @Override
    public Information setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Information other = (Information) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        if (describe == null) {
            if (other.describe != null)
                return false;
        }
        else if (!describe.equals(other.describe))
            return false;
        if (img == null) {
            if (other.img != null)
                return false;
        }
        else if (!img.equals(other.img))
            return false;
        if (video == null) {
            if (other.video != null)
                return false;
        }
        else if (!video.equals(other.video))
            return false;
        if (type == null) {
            if (other.type != null)
                return false;
        }
        else if (!type.equals(other.type))
            return false;
        if (pv == null) {
            if (other.pv != null)
                return false;
        }
        else if (!pv.equals(other.pv))
            return false;
        if (createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!createdAt.equals(other.createdAt))
            return false;
        if (updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.describe == null) ? 0 : this.describe.hashCode());
        result = prime * result + ((this.img == null) ? 0 : this.img.hashCode());
        result = prime * result + ((this.video == null) ? 0 : this.video.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        result = prime * result + ((this.pv == null) ? 0 : this.pv.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Information (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(describe);
        sb.append(", ").append(img);
        sb.append(", ").append(video);
        sb.append(", ").append(type);
        sb.append(", ").append(pv);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IInformation from) {
        setId(from.getId());
        setName(from.getName());
        setDescribe(from.getDescribe());
        setImg(from.getImg());
        setVideo(from.getVideo());
        setType(from.getType());
        setPv(from.getPv());
        setCreatedAt(from.getCreatedAt());
        setUpdatedAt(from.getUpdatedAt());
    }

    @Override
    public <E extends IInformation> E into(E into) {
        into.from(this);
        return into;
    }
}
