/*
 * This file is generated by jOOQ.
 */
package generated.tables.records;


import generated.tables.Information;
import generated.tables.interfaces.IInformation;

import java.time.LocalDateTime;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InformationRecord extends UpdatableRecordImpl<InformationRecord> implements Record9<Long, String, String, String, String, Integer, Long, LocalDateTime, LocalDateTime>, IInformation {

    private static final long serialVersionUID = -2093781674;

    /**
     * Setter for <code>bysj.information.id</code>.
     */
    @Override
    public InformationRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>bysj.information.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>bysj.information.name</code>. ??
     */
    @Override
    public InformationRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>bysj.information.name</code>. ??
     */
    @NotNull
    @Size(max = 255)
    @Override
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>bysj.information.describe</code>. ??
     */
    @Override
    public InformationRecord setDescribe(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>bysj.information.describe</code>. ??
     */
    @Size(max = 255)
    @Override
    public String getDescribe() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bysj.information.img</code>. ?????
     */
    @Override
    public InformationRecord setImg(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>bysj.information.img</code>. ?????
     */
    @NotNull
    @Size(max = 65535)
    @Override
    public String getImg() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bysj.information.video</code>. ????
     */
    @Override
    public InformationRecord setVideo(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>bysj.information.video</code>. ????
     */
    @NotNull
    @Size(max = 65535)
    @Override
    public String getVideo() {
        return (String) get(4);
    }

    /**
     * Setter for <code>bysj.information.type</code>. ???? 1-??? 2-?? 3-? 4-? 5-?? 6-??
     */
    @Override
    public InformationRecord setType(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>bysj.information.type</code>. ???? 1-??? 2-?? 3-? 4-? 5-?? 6-??
     */
    @Override
    public Integer getType() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>bysj.information.pv</code>. ?????
     */
    @Override
    public InformationRecord setPv(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>bysj.information.pv</code>. ?????
     */
    @Override
    public Long getPv() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>bysj.information.created_at</code>. ????
     */
    @Override
    public InformationRecord setCreatedAt(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>bysj.information.created_at</code>. ????
     */
    @Override
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>bysj.information.updated_at</code>. ????
     */
    @Override
    public InformationRecord setUpdatedAt(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>bysj.information.updated_at</code>. ????
     */
    @Override
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, String, String, String, String, Integer, Long, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, String, String, String, String, Integer, Long, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Information.INFORMATION.ID;
    }

    @Override
    public Field<String> field2() {
        return Information.INFORMATION.NAME;
    }

    @Override
    public Field<String> field3() {
        return Information.INFORMATION.DESCRIBE;
    }

    @Override
    public Field<String> field4() {
        return Information.INFORMATION.IMG;
    }

    @Override
    public Field<String> field5() {
        return Information.INFORMATION.VIDEO;
    }

    @Override
    public Field<Integer> field6() {
        return Information.INFORMATION.TYPE;
    }

    @Override
    public Field<Long> field7() {
        return Information.INFORMATION.PV;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return Information.INFORMATION.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return Information.INFORMATION.UPDATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getDescribe();
    }

    @Override
    public String component4() {
        return getImg();
    }

    @Override
    public String component5() {
        return getVideo();
    }

    @Override
    public Integer component6() {
        return getType();
    }

    @Override
    public Long component7() {
        return getPv();
    }

    @Override
    public LocalDateTime component8() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component9() {
        return getUpdatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getDescribe();
    }

    @Override
    public String value4() {
        return getImg();
    }

    @Override
    public String value5() {
        return getVideo();
    }

    @Override
    public Integer value6() {
        return getType();
    }

    @Override
    public Long value7() {
        return getPv();
    }

    @Override
    public LocalDateTime value8() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value9() {
        return getUpdatedAt();
    }

    @Override
    public InformationRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public InformationRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public InformationRecord value3(String value) {
        setDescribe(value);
        return this;
    }

    @Override
    public InformationRecord value4(String value) {
        setImg(value);
        return this;
    }

    @Override
    public InformationRecord value5(String value) {
        setVideo(value);
        return this;
    }

    @Override
    public InformationRecord value6(Integer value) {
        setType(value);
        return this;
    }

    @Override
    public InformationRecord value7(Long value) {
        setPv(value);
        return this;
    }

    @Override
    public InformationRecord value8(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public InformationRecord value9(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public InformationRecord values(Long value1, String value2, String value3, String value4, String value5, Integer value6, Long value7, LocalDateTime value8, LocalDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IInformation from) {
        setId(from.getId());
        setName(from.getName());
        setDescribe(from.getDescribe());
        setImg(from.getImg());
        setVideo(from.getVideo());
        setType(from.getType());
        setPv(from.getPv());
        setCreatedAt(from.getCreatedAt());
        setUpdatedAt(from.getUpdatedAt());
    }

    @Override
    public <E extends IInformation> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InformationRecord
     */
    public InformationRecord() {
        super(Information.INFORMATION);
    }

    /**
     * Create a detached, initialised InformationRecord
     */
    public InformationRecord(Long id, String name, String describe, String img, String video, Integer type, Long pv, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Information.INFORMATION);

        set(0, id);
        set(1, name);
        set(2, describe);
        set(3, img);
        set(4, video);
        set(5, type);
        set(6, pv);
        set(7, createdAt);
        set(8, updatedAt);
    }
}
